# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7eae5717537ec11ef3d0386f0711c1613b8bd2443e729276d75a9f3ca3d5e5884f54bdbde68c3d46a4d94d1f53277647da30140a3858ec29b6085aabcdf72c7

test:
  secret_key_base: ed5184d5391ecda4e934b8e2ebc3b349e053bf805b7c940a2709c16b24d6cb6fb5ceb2fbf7efc0b3e687d6bf87a2090b5fbf9163d9c7defd585951949ed7194b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
